name: ActionsCI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [develop]

jobs:
  ci-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - name: Homebrew
        run: brew install qt6 libiconv
      - name: build
        run: |
          qmake CONFIG+=release
          make -j4
      - name: version
        run: shogimaru.app/Contents/MacOS/shogimaru -v

  ci-ubuntu-gcc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - name: apt
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends qt6-base-dev qt6-multimedia-dev libqt6gui6 libqt6network6 libqt6widgets6 qmake6 libgl1-mesa-dev g++ make cmake
      - name: build
        run: |
          qmake6 CONFIG+=release
          make -j4
      - name: version
        run: ./shogimaru -v

  ci-ubuntu-clang:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - name: apt
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends qt6-base-dev qt6-multimedia-dev libqt6gui6 libqt6network6 libqt6widgets6 qmake6 libgl1-mesa-dev clang make cmake
      - name: build
        run: |
          qmake6 -spec linux-clang CONFIG+=release
          make -j4
      - name: version
        run: ./shogimaru -v
